version: '3.8'

services:
    server:        
# look for dockerfile and build the container
        build: ./server
        container_name: server
        command: 'python app/main.py'
        # mount the volumes so we can change the code and hot reload
        volumes:
            - './server:/usr/src/app'
        # expose port on the container, only to other ocntainers
        working_dir: /usr/src/app
        ports:
            - '8000:8000'
    client:
        build: ./client/
        container_name: client
        restart: always
        ports:
            - '3000:3000'
        command: 'npm run start'
