version: '2.3'

services:
    server:        
# look for dockerfile and build the container
        build: ./server
        container_name: server
        # command: 'python app/main.py'
        # mount the volumes so we can change the code and hot reload
        # volumes:
        #    - './server:/usr/src/app'
        # expose port on the container, only to other ocntainers
        # working_dir: /usr/src/app
        networks:
            - internal
    nginx:
      container_name: nginx
      restart: always
      image: nginx:latest
      ports:
        - 8000:80
      volumes:
        - .:/next-gen-seer
        - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      depends_on:
        - server
      networks:
        - internal
    client:
        build: ./client
        container_name: client
        restart: always
        ports:
           - '3000:3000'
        command: 'npm run start'
        volumes:
            - /app/node_modules
            - ./client:/app
        depends_on:
            - server
        networks:
            - internal
networks:
    internal:
