version: '2.3'

services:
    server:        
      build: ./server
      container_name: server
      ports:
        - 8000:8000
      volumes:
        - ./server:/api
      env_file:
        - ./variables/development.env
    client:
      build: ./client
      container_name: client
      restart: always
      command: 'npm run dev'
      ports:
        - 3000:3000
      volumes:
          - /app/node_modules
          - ./client:/app
      depends_on:
          - server
      env_file:
        - ./variables/development.env
    document:        
      build: ./server
      container_name: document
      ports:
        - 8115:8115
      command: ["python3", "/api/app/repository/repo_server.py"]
      volumes:
        - ./server:/api
        - /data/csxrepo01_repo:/data/csxrepo01_repo
        - ./next-gen-citeseer:/next-gen-citeseer
      env_file:
        - ./variables/development.env 
 
 
 
 
 
 
 


