version: '2.3'

services:
    server:        
      env_file: variables/development.env
      build: ./server
      container_name: server
      ports:
        - ${API_PORT}:8000
      volumes:
        - ./server:/api
    client:
      env_file: variables/development.env
      build: ./client
      container_name: client
      restart: always
      command: 'npm run start'
      ports:
        - ${UI_PORT}:3000
      volumes:
          - /app/node_modules
          - ./client:/app
      depends_on:
          - server
    nginx:
      env_file: variables/development.env
      container_name: web
      restart: always
      image: nginx:latest
      ports:
        - ${NGINX_PORT}:8080
      volumes:
        - .:/next-gen-seer
        - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      depends_on:
        - server
        - client


