version: '2.3'

services:
    server:        
      env_file: variables/production.env
    client:
      command: 'npm run client'
      env_file: variables/production.env
    nginx:
      env_file: variables/production.env

