#CLUSTERS_INDEX = "acl_papers_faceted"
CLUSTERS_INDEX = "csx_citeseer_all_docs"
KEYMAP_INDEX = "key_map04"
REQUESTS_INDEX = "requestsdemo"
REPO_SERVER_BASE_PATH = "/data/repo/"
REPO_SERVER_HOST = "localhost"
