#CLUSTERS_INDEX = "acl_papers_faceted_latest"
#CLUSTERS_INDEX = "csx_citeseer_all_docs"
#CLUSTERS_INDEX = "csx_citeseer_docs"
#CLUSTERS_INDEX = "csx_citeseer_docs_old"
CLUSTERS_INDEX = "csx_citeseer_docs_old_pubinfo"
#KEYMAP_INDEX = "key_map04"
KEYMAP_INDEX = "csx_citeseer_papers_keymap"
REQUESTS_INDEX = "requestsdemo"
#REPO_SERVER_BASE_PATH = "/mnt/rep1/"
REPO_SERVER_BASE_PATH = "/data/csxrepo01_repo/csx_beta_repo/"
REPO_SERVER_HOST = "localhost"

